name: Node package tests
description: Run node package tests

runs:
  using: "composite"

  steps:
    - name: Use Node 20
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: npm
    - name: Run Node package tests on Node 20
      shell: bash
      run: |
        node --version
        npm run nodejs-tests

    - name: Use Node 22
      uses: actions/setup-node@v4
      with:
        node-version: 22
        cache: npm
    - name: Run Node package tests on Node 22
      shell: bash
      run: |
        node --version
        npm run nodejs-tests

    - name: Use Node 24
      uses: actions/setup-node@v4
      with:
        node-version: 24
        cache: npm
    - name: Run Node package tests on Node 24
      shell: bash
      run: |
        node --version
        npm run nodejs-tests

    - name: Use Node latest
      uses: actions/setup-node@v4
      with:
        node-version: latest
        cache: npm
    - name: Run Node package tests on Node-latest
      shell: bash
      run: |
        node --version
        npm run nodejs-tests
