---
name: "Run benchmarks"
description: |
  Runs the benchmarks

runs:
  using: 'composite'
  steps:
    - name: Restore benchmark cache
      uses: actions/cache/restore@v4
      id: berlin-cache-restore
      with:
        path: ${{ env.TEST_DIR }}/data/berlin.osm.pbf
        key: berlin-osm-pbf-

    - name: Download benchmark data
      if: steps.berlin-cache-restore.outputs.cache-hit != 'true'
      shell: bash
      run: |
        curl https://download.geofabrik.de/europe/germany/berlin-latest.osm.pbf \
            -o ${TEST_DIR}/data/berlin.osm.pbf --location --silent

    - name: Run benchmarks
      shell: bash
      run: |
        set -o errexit

        ctest --test-dir ${OSRM_BENCHMARKS_BINARY_DIR} --build-config ${BUILD_TYPE} \
          -j $JOBS --verbose --output-log ${LOG_DIR}/benchmarks.log --no-tests=error

        "${CI_DIR}/run_e2e_benchmarks.sh"

        for i in "${LOG_DIR}/"*.bench; do
          echo "::group::$i"
          cat $i
          echo "::endgroup::"
        done

        killall -9 osrm-routed || true

    - name: Save benchmark cache
      if: always() && steps.berlin-cache-restore.outputs.cache-hit != 'true'
      uses: actions/cache/save@v4
      with:
        path: ${{ env.TEST_DIR }}/data/berlin.osm.pbf
        key: ${{ steps.berlin-cache-restore.outputs.cache-primary-key }}
