name: osrm-backend CI
on:
  push:
    branches:
      - master
    tags:
      - v[1-9]+.[0-9]+.[0-9]+
      - v[1-9]+.[0-9]+.[0-9]+-[a-zA-Z]+.[0-9]+
      - v[1-9]+.[0-9]+-[0-9a-zA-Z]+
  pull_request:
    branches:
      - master

env:
  # paths
  BUILD_DIR:  ${{ github.workspace }}/build
  TEST_DIR:   ${{ github.workspace }}/test
  LOG_DIR:    ${{ github.workspace }}/test/logs
  CI_DIR:     ${{ github.workspace }}/scripts/ci
  NODE_DIR:   ${{ github.workspace }}/.npm
  NAPI_DIR:   ${{ github.workspace }}/lib/binding_napi_v8
  CONAN_HOME: ${{ github.workspace }}.conan2

  CONAN_VERSION: 2.24.0
  CCACHE_DIR: ${{ github.workspace }}/.ccache
  CCACHE_TEMPDIR: /tmp/.ccache-temp
  CCACHE_COMPRESS: 1
  ENABLE_CCACHE: ON

  CASHER_TIME_OUT: 599 # one second less than 10m to avoid 10m timeout error: https://github.com/Project-OSRM/osrm-backend/issues/2742

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  format-taginfo-docs:
    uses: ./.github/workflows/format-taginfo-docs.yml

  docker:
    uses: ./.github/workflows/docker.yml

  windows:
    uses: ./.github/workflows/conan-windows.yml

  build-matrix:
    strategy:
      matrix:
        include:
          - name: clang-20-release
            node: 24
            runs-on: ubuntu-24.04
            BOOST_PLATFORM: 24.04
            CCOMPILER: clang-20
            CXXCOMPILER: clang++-20

          - name: clang-19-release
            node: 24
            runs-on: ubuntu-24.04
            BOOST_PLATFORM: 24.04
            CCOMPILER: clang-19
            CXXCOMPILER: clang++-19

          - name: clang-19-debug-asan
            continue-on-error: true
            node: 24
            runs-on: ubuntu-24.04
            BOOST_PLATFORM: 24.04
            CCOMPILER: clang-19
            CXXCOMPILER: clang++-19
            ENABLE_ASAN: ON
            ENABLE_LTO: OFF

          - name: clang-19-debug-ubsan
            continue-on-error: true
            node: 24
            runs-on: ubuntu-24.04
            BOOST_PLATFORM: 24.04
            CCOMPILER: clang-19
            CXXCOMPILER: clang++-19
            ENABLE_UBSAN: ON
            ENABLE_LTO: OFF

          - name: clang-19-debug-tidy
            continue-on-error: true
            node: 24
            runs-on: ubuntu-24.04
            BOOST_PLATFORM: 24.04
            CCOMPILER: clang-19
            CXXCOMPILER: clang++-19
            ENABLE_CLANG_TIDY: ON
            UNIT_TESTS: OFF
            CUCUMBER_TESTS: OFF
            ENABLE_LTO: OFF

          - name: clang-18-release
            node: 22
            runs-on: ubuntu-24.04
            BOOST_PLATFORM: 24.04
            CCOMPILER: clang-18
            CXXCOMPILER: clang++-18
            ENABLE_LTO: OFF

          - name: clang-17-release
            node: 22
            runs-on: ubuntu-24.04
            BOOST_PLATFORM: 24.04
            CCOMPILER: clang-17
            CXXCOMPILER: clang++-17
            ENABLE_LTO: OFF

          - name: clang-16-release
            node: 20
            runs-on: ubuntu-24.04
            BOOST_PLATFORM: 24.04
            CCOMPILER: clang-16
            CXXCOMPILER: clang++-16
            ENABLE_LTO: OFF

          - name: gcc-14-release
            node: 24
            runs-on: ubuntu-24.04
            BOOST_PLATFORM: 24.04
            CCOMPILER: gcc-14
            CXXCOMPILER: g++-14

          - name: gcc-13-release
            node: 22
            runs-on: ubuntu-24.04
            BOOST_PLATFORM: 24.04
            CCOMPILER: gcc-13
            CXXCOMPILER: g++-13

          - name: gcc-13-debug-cov
            node: 22
            runs-on: ubuntu-24.04
            BOOST_PLATFORM: 24.04
            CCOMPILER: gcc-13
            CXXCOMPILER: g++-13
            ENABLE_COVERAGE: ON

          - name: gcc-12-release
            node: 20
            runs-on: ubuntu-22.04
            BOOST_PLATFORM: 22.04
            CCOMPILER: gcc-12
            CXXCOMPILER: g++-12
            CXXFLAGS: '-Wno-array-bounds -Wno-uninitialized'

          - name: conan-linux-release-node
            node: 22
            runs-on: ubuntu-24.04
            CCOMPILER: clang-19
            CXXCOMPILER: clang++-19

          - name: conan-linux-debug-node
            node: 22
            runs-on: ubuntu-24.04
            CCOMPILER: clang-19
            CXXCOMPILER: clang++-19

          - name: conan-macos-14-arm64-release-node
            node: 22
            runs-on: macos-14 # arm64
            CCOMPILER: clang
            CXXCOMPILER: clang++
            ENABLE_ASSERTIONS: ON

          - name: conan-macos-15-x64-release-node
            node: 22
            runs-on: macos-15-intel # x86_64
            CCOMPILER: clang
            CXXCOMPILER: clang++
            ENABLE_ASSERTIONS: ON

          - name: conan-macos-15-arm64-release-node
            node: 22
            runs-on: macos-15 # arm64
            CCOMPILER: clang
            CXXCOMPILER: clang++
            ENABLE_ASSERTIONS: ON

          - name: conan-macos-26-arm64-release-node
            node: 24
            runs-on: macos-26 # arm64
            CCOMPILER: clang
            CXXCOMPILER: clang++
            ENABLE_ASSERTIONS: ON

    name: ${{ matrix.name }}
    continue-on-error: ${{ !matrix.continue-on-error == null && false || true }}
    runs-on: ${{ matrix.runs-on }}
    env:
      PUBLISH: OFF

      BUILD_TYPE:           ${{ contains(matrix.name, 'debug') && 'Debug' || 'Release' }}
      ENABLE_CONAN:         ${{ contains(matrix.name, 'conan') && 'ON' || 'OFF' }}
      ENABLE_NODE_BINDINGS: ${{ contains(matrix.name, 'node')  && 'ON' || 'OFF' }}
      NODE_PACKAGE_TESTS:   ${{ contains(matrix.name, 'node')  && 'ON' || 'OFF' }}
      BUILD_NODE_PACKAGE:   ${{ contains(matrix.name, 'node')  && 'ON' || 'OFF' }}

      BUILD_SHARED_LIBS: ${{ matrix.BUILD_SHARED_LIBS }}
      CCOMPILER:         ${{ matrix.CCOMPILER }}
      CFLAGS:            ${{ matrix.CFLAGS }}
      CXXCOMPILER:       ${{ matrix.CXXCOMPILER }}
      CXXFLAGS:          ${{ matrix.CXXFLAGS }}

      ENABLE_ASSERTIONS: ${{ matrix.ENABLE_ASSERTIONS }}
      ENABLE_CLANG_TIDY: ${{ matrix.ENABLE_CLANG_TIDY }}
      ENABLE_COVERAGE:   ${{ matrix.ENABLE_COVERAGE }}
      ENABLE_LTO:        ${{ matrix.ENABLE_LTO }}
      ENABLE_ASAN:       ${{ matrix.ENABLE_ASAN }}
      ENABLE_UBSAN:      ${{ matrix.ENABLE_UBSAN }}
      UNIT_TESTS:        ${{ (matrix.UNIT_TESTS != 'OFF'        ) && 'ON' || 'OFF' }}
      CUCUMBER_TESTS:    ${{ (matrix.CUCUMBER_TESTS != 'OFF'    ) && 'ON' || 'OFF' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup environment
        run: |
          mkdir -p $BUILD_DIR $TEST_DIR $LOG_DIR $CCACHE_DIR
          uname -m

          if [[ "$ENABLE_ASAN" == "ON" || "$ENABLE_UBSAN" == "ON" ]]; then
            echo "ASAN_OPTIONS=log_path=${LOG_DIR}/asan.log:print_suppressions=0:suppressions=${CI_DIR}/addresssanitizer.conf" >> $GITHUB_ENV
            echo "LSAN_OPTIONS=log_path=${LOG_DIR}/lsan.log:print_suppressions=0:suppressions=${CI_DIR}/leaksanitizer.conf" >> $GITHUB_ENV
            echo "UBSAN_OPTIONS=log_path=${LOG_DIR}/ubsan.log:symbolize=1:halt_on_error=1:print_stacktrace=1:suppressions=${CI_DIR}/undefinedsanitizer.conf" >> $GITHUB_ENV
          fi

          if [[ "${RUNNER_OS}" == "Linux" ]]; then
            echo "JOBS=$((`nproc` + 1))" >>  $GITHUB_ENV
          elif [[ "${RUNNER_OS}" == "macOS" ]]; then
            echo "JOBS=$((`sysctl -n hw.ncpu` + 1))" >>  $GITHUB_ENV
          fi

      # Node

      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: matrix.node
          cache: npm

      - name: Setup node environment
        run: |
          PACKAGE_JSON_VERSION=$(node -e "console.log(require('./package.json').version)")
          echo PUBLISH=$([[ "${GITHUB_REF:-}" == "refs/tags/v${PACKAGE_JSON_VERSION}" ]] && echo "On" || echo "Off") >> $GITHUB_ENV

      # Conan

      - name: Install Conan
        uses: conan-io/setup-conan@v1
        if: env.ENABLE_CONAN == 'ON'
        with:
          version: env.CONAN_VERSION
          home: env.CONAN_HOME
          cache_packages: true
          use_venv: true

      - name: Restore Conan cache
        id: conan-cache-restore
        uses: actions/cache/restore@v4
        if: env.ENABLE_CONAN == 'ON'
        with:
          path: env.CONAN_HOME
          key: conan-${{ matrix.runs-on }}-${{ env.BUILD_TYPE }}-${{ hashFiles('conanfile.py') }}

      - name: Setup Conan environment
        if: env.ENABLE_CONAN == 'ON'
        working-directory: env.BUILD_DIR
        run: |
          echo "::group::debug info"
          echo "PATH=$PATH"
          which conan
          conan --version
          echo "::endgroup::"

          conan profile detect --force
          conan install .. --output-folder=. --build=missing -s:a compiler.cppstd=20 -s:a build_type=${BUILD_TYPE}

          echo "::group::Conan cache contents"
          conan list
          echo "::endgroup::"

          echo "::group::Conan DLL paths"
          cat *.runpath
          echo "::endgroup::"

          # magic, adds DLL paths, see: conanfile.py
          while read -r line; do echo "$line" >> "$GITHUB_PATH"; done < *.runpath

          echo "CMAKE_EXTRA_DEFS=-DENABLE_CONAN=ON -DCMAKE_TOOLCHAIN_FILE=conan_toolchain.cmake -DSKIP_CONAN_INSTALL=ON" >> $GITHUB_ENV

      - name: Save Conan cache
        uses: actions/cache/save@v4
        if: always() && env.ENABLE_CONAN == 'ON' && steps.conan-cache-restore.outputs.cache-hit != 'true'
        with:
          path: env.CONAN_HOME
          key: steps.cache-conan-restore.outputs.cache-primary-key

      # CCache

      - name: Restore CCache
        id: cache-ccache-restore
        uses: actions/cache/restore@v4
        if: env.ENABLE_CCACHE == 'ON'
        with:
          path: env.CCACHE_DIR
          key: ccache-${{ matrix.name }}-${{ github.sha }}
          restore-keys: |
            ccache-${{ matrix.name }}-

      # See: https://github.com/actions/toolkit/issues/946#issuecomment-1590016041
      # We need it to be able to access system folders while restoring cached Boost below
      - name: Give tar root ownership
        if: runner.os == 'Linux' && env.ENABLE_CONAN != 'ON'
        run: sudo chown root /bin/tar && sudo chmod u+s /bin/tar

      - name: Install boost
        if: env.ENABLE_CONAN != 'ON'
        uses: MarkusJx/install-boost@v2
        id: install-boost
        with:
          boost_version: 1.88.0
          platform_version: matrix.BOOST_PLATFORM

      - name: Install dev dependencies
        run: |
          # Install compiler and ccache
          if [[ "${RUNNER_OS}" == "Linux" ]]; then
            sudo apt-get update -y
            sudo apt-get install -y ${CCOMPILER} ${CXXCOMPILER} ccache
          elif [[ "${RUNNER_OS}" == "macOS" ]]; then
            brew install ccache
          fi

      - name: Install dev dependencies
        if: env.ENABLE_CONAN != 'ON'
        run: |
          # workaround for issue that GitHub Actions seems to not adding it to PATH after https://github.com/actions/runner-images/pull/6499
          # and that's why CI cannot find conan executable installed above
          # if [[ "${RUNNER_OS}" == "macOS" ]]; then
          #   echo "/Library/Frameworks/Python.framework/Versions/Current/bin" >> $GITHUB_PATH
          # fi

          echo "Boost_DIR=${{ steps.install-boost.outputs.BOOST_ROOT }}" >> $GITHUB_ENV

          # Linux dev packages
          sudo apt-get install -y libbz2-dev libxml2-dev libzip-dev liblua5.2-dev
          if [[ "${ENABLE_COVERAGE}" == "ON" ]]; then
            sudo apt-get install -y lcov
          fi

          # TBB
          TBB_VERSION=2021.12.0
          if [[ "${RUNNER_OS}" == "Linux" ]]; then
            TBB_URL="https://github.com/oneapi-src/oneTBB/releases/download/v${TBB_VERSION}/oneapi-tbb-${TBB_VERSION}-lin.tgz"
          elif [[ "${RUNNER_OS}" == "macOS" ]]; then
            TBB_URL="https://github.com/oneapi-src/oneTBB/releases/download/v${TBB_VERSION}/oneapi-tbb-${TBB_VERSION}-mac.tgz"
          fi
          wget --tries 5 ${TBB_URL} -O onetbb.tgz
          tar zxvf onetbb.tgz
          sudo cp -a oneapi-tbb-${TBB_VERSION}/lib/. /usr/local/lib/
          sudo cp -a oneapi-tbb-${TBB_VERSION}/include/. /usr/local/include/

          echo "CMAKE_EXTRA_DEFS=" >> $GITHUB_ENV

      - name: Prepare build
        run: |
          ccache --max-size=256M
          ccache --zero-stats
          npm ci --ignore-scripts
          if [[ "${ENABLE_COVERAGE}" == "ON" ]]; then
            lcov --directory . --zerocounters # clean cached files
          fi
          echo "CC=${CCOMPILER}" >> $GITHUB_ENV
          echo "CXX=${CXXCOMPILER}" >> $GITHUB_ENV
          if [[ "${RUNNER_OS}" == "macOS" ]]; then
            # missing from GCC path, needed for conan builds of libiconv, for example.
            sudo xcode-select --switch /Library/Developer/CommandLineTools
            echo "LIBRARY_PATH=${LIBRARY_PATH}:/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/lib" >> $GITHUB_ENV
            echo "CPATH=${CPATH}:/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include" >> $GITHUB_ENV
          fi

      - name: Cmake
        working-directory: env.BUILD_DIR
        run: |
          cmake .. -DCMAKE_BUILD_TYPE=${BUILD_TYPE} \
                   -DENABLE_ASSERTIONS=${ENABLE_ASSERTIONS:-OFF} \
                   -DENABLE_CLANG_TIDY=${ENABLE_CLANG_TIDY:-OFF} \
                   -DBUILD_SHARED_LIBS=${BUILD_SHARED_LIBS:-OFF} \
                   -DENABLE_COVERAGE=${ENABLE_COVERAGE:-OFF} \
                   -DENABLE_NODE_BINDINGS=${ENABLE_NODE_BINDINGS:-OFF} \
                   -DENABLE_ASAN=${ENABLE_ASAN:-OFF} \
                   -DENABLE_UBSAN=${ENABLE_UBSAN:-OFF} \
                   -DENABLE_CCACHE=${ENABLE_CCACHE:-ON} \
                   -DENABLE_LTO=${ENABLE_LTO:-ON} \
                   ${CMAKE_EXTRA_DEFS}

      - name: Build
        working-directory: env.BUILD_DIR
        run: |
          echo "::group::make"
          mkdir -p ${OSRM_BUILD_DIR}
          make --jobs=${JOBS}
          echo "::endgroup::"

          if [[ "${RUNNER_OS}" == "Linux" ]]; then
            if [[ "$ENABLE_ASAN" == 'ON' ]]; then
              export LD_LIBRARY_PATH=$(dirname `clang -print-file-name=libclang_rt.asan-x86_64.so`):$LD_LIBRARY_PATH
            fi
            if [[ "$ENABLE_UBSAN" == 'ON' ]]; then
              export LD_LIBRARY_PATH=$(dirname `clang -print-file-name=libclang_rt.ubsan_standalone-x86_64.so`):$LD_LIBRARY_PATH
            fi
            echo "LD_LIBRARY_PATH=$LD_LIBRARY_PATH" >> $GITHUB_ENV
          fi

          if [[ "${UNIT_TESTS}" == "ON" ]]; then
            echo "::group::make tests"
            make --jobs=${JOBS} tests
            echo "::endgroup::"

            echo "::group::make benchmarks"
            make --jobs=${JOBS} benchmarks
            echo "::endgroup::"
          fi

      - name: Save CCache
        uses: actions/cache/save@v4
        if: always() && env.ENABLE_CCACHE == 'ON' && steps.cache-ccache-restore.outputs.cache-hit != 'true'
        with:
          path: env.CCACHE_DIR
          key: steps.cache-ccache-restore.outputs.cache-primary-key

      - name: Show CCache statistics
        if: always() && env.ENABLE_CCACHE == 'ON'
        run: |
          ccache -s
          echo "::group::ccache -p"
          ccache -p
          echo "::endgroup::"

      - name: Run unit tests
        if: env.UNIT_TESTS == 'ON'
        run: |
          make -C ${TEST_DIR}/data

          set +o errexit
          cd ${{ env.OSRM_BUILD_DIR }}/unit_tests${{ env.OSRM_BUILD_SUBDIR }}
          for i in *-tests${EXECUTABLE_SUFFIX}
          do echo "::group::Running $i"
            ./$i
            echo "::endgroup::"
          done

      - name: Run Cucumber tests
        if: env.CUCUMBER_TESTS == 'ON'
        run: |
          npm test -- --parallel $JOBS

      - name: Run Node package tests
        if: env.NODE_PACKAGE_TESTS == 'ON'
        uses: ./.github/actions/node-package-tests

      - name: Upload test logs
        uses: actions/upload-artifact@v4
        if: always()
        with:
          if-no-files-found: ignore
          name: ${{ matrix.name }}-test-logs
          path: env.LOG_DIR

      - name: Build Node package
        if: env.BUILD_NODE_PACKAGE == 'ON'
        run: ${{ env.CI_DIR }}/node_package.sh

      - name: Publish Node package
        if: env.BUILD_NODE_PACKAGE == 'ON' && env.PUBLISH == 'ON'
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifactErrorsFailBuild: true
          artifacts: build/stage/**/*.tar.gz
          omitBody: true
          omitBodyDuringUpdate: true
          omitName: true
          omitNameDuringUpdate: true
          replacesArtifacts: true
          token: secrets.GITHUB_TOKEN

  ci-complete:
    runs-on: ubuntu-latest
    needs: [format-taginfo-docs, docker, windows, build-matrix]
    steps:
      - run: echo "CI complete"
