name: osrm-backend CI
on:
  push:
    branches:
      - master
    tags:
      - v[1-9]+.[0-9]+.[0-9]+
      - v[1-9]+.[0-9]+.[0-9]+-[a-zA-Z]+.[0-9]+
      - v[1-9]+.[0-9]+-[0-9a-zA-Z]+
  pull_request:
    branches:
      - master

env:
  # paths
  BUILD_DIR: ${{ github.workspace }}/build
  TEST_DIR: ${{ github.workspace }}/test
  LOG_DIR: ${{ github.workspace }}/test/logs
  NODE_DIR: ${{ github.workspace }}/.npm
  CONAN_HOME: ${{ github.workspace }}/.conan2

  CCACHE_DIR: ${{ github.workspace }}/.ccache
  CCACHE_TEMPDIR: /tmp/.ccache-temp
  CCACHE_COMPRESS: 1
  ENABLE_CCACHE: ON

  CASHER_TIME_OUT: 599 # one second less than 10m to avoid 10m timeout error: https://github.com/Project-OSRM/osrm-backend/issues/2742

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  format-taginfo-docs:
    uses: ./.github/workflows/format-taginfo-docs.yml

  docker:
    uses: ./.github/workflows/docker.yml

  windows:
    uses: ./.github/workflows/conan-windows.yml

  build-matrix:
    strategy:
      matrix:
        include:
          - name: clang-20-release
            node: 24
            runs-on: ubuntu-24.04
            BOOST_PLATFORM: 24.04
            CCOMPILER: clang-20
            CXXCOMPILER: clang++-20

          - name: clang-19-release
            node: 24
            runs-on: ubuntu-24.04
            BOOST_PLATFORM: 24.04
            CCOMPILER: clang-19
            CXXCOMPILER: clang++-19

          - name: clang-19-debug-asan
            continue-on-error: true
            node: 24
            runs-on: ubuntu-24.04
            BOOST_PLATFORM: 24.04
            CCOMPILER: clang-19
            CXXCOMPILER: clang++-19
            ENABLE_ASAN: ON
            ENABLE_LTO: OFF
            NODEJS_TESTS: OFF

          - name: clang-19-debug-ubsan
            continue-on-error: true
            node: 24
            runs-on: ubuntu-24.04
            BOOST_PLATFORM: 24.04
            CCOMPILER: clang-19
            CXXCOMPILER: clang++-19
            ENABLE_UBSAN: ON
            ENABLE_LTO: OFF
            NODEJS_TESTS: OFF

          - name: clang-19-debug-tidy
            continue-on-error: true
            node: 24
            runs-on: ubuntu-24.04
            BOOST_PLATFORM: 24.04
            CCOMPILER: clang-19
            CXXCOMPILER: clang++-19
            ENABLE_CLANG_TIDY: ON
            UNIT_TESTS: OFF
            NODEJS_TESTS: OFF
            CUCUMBER_TESTS: OFF
            ENABLE_LTO: OFF

          - name: clang-18-release
            node: 22
            runs-on: ubuntu-24.04
            BOOST_PLATFORM: 24.04
            CCOMPILER: clang-18
            CXXCOMPILER: clang++-18
            ENABLE_LTO: OFF

          - name: clang-17-release
            node: 22
            runs-on: ubuntu-24.04
            BOOST_PLATFORM: 24.04
            CCOMPILER: clang-17
            CXXCOMPILER: clang++-17
            ENABLE_LTO: OFF

          - name: clang-16-release
            node: 20
            runs-on: ubuntu-24.04
            BOOST_PLATFORM: 24.04
            CCOMPILER: clang-16
            CXXCOMPILER: clang++-16
            ENABLE_LTO: OFF

          - name: gcc-14-release
            node: 24
            runs-on: ubuntu-24.04
            BOOST_PLATFORM: 24.04
            CCOMPILER: gcc-14
            CXXCOMPILER: g++-14

          - name: gcc-13-release
            node: 22
            runs-on: ubuntu-24.04
            BOOST_PLATFORM: 24.04
            CCOMPILER: gcc-13
            CXXCOMPILER: g++-13

          - name: gcc-13-debug-cov
            node: 22
            runs-on: ubuntu-24.04
            BOOST_PLATFORM: 24.04
            CCOMPILER: gcc-13
            CXXCOMPILER: g++-13
            ENABLE_COVERAGE: ON

          - name: gcc-12-release
            node: 20
            runs-on: ubuntu-22.04
            BOOST_PLATFORM: 22.04
            CCOMPILER: gcc-12
            CXXCOMPILER: g++-12
            CXXFLAGS: '-Wno-array-bounds -Wno-uninitialized'

          - name: conan-linux-release-node
            node: 22
            runs-on: ubuntu-24.04
            CCOMPILER: clang-19
            CXXCOMPILER: clang++-19

          - name: conan-linux-debug-node
            node: 22
            runs-on: ubuntu-24.04
            CCOMPILER: clang-19
            CXXCOMPILER: clang++-19

          - name: conan-macos-14-arm64-release-node
            node: 22
            runs-on: macos-14 # arm64
            CCOMPILER: clang
            CXXCOMPILER: clang++
            ENABLE_ASSERTIONS: ON

          - name: conan-macos-15-x64-release-node
            node: 22
            runs-on: macos-15-intel # x86_64
            CCOMPILER: clang
            CXXCOMPILER: clang++
            ENABLE_ASSERTIONS: ON

          - name: conan-macos-15-arm64-release-node
            node: 22
            runs-on: macos-15 # arm64
            CCOMPILER: clang
            CXXCOMPILER: clang++
            ENABLE_ASSERTIONS: ON

          - name: conan-macos-26-arm64-release-node
            node: 24
            runs-on: macos-26 # arm64
            CCOMPILER: clang
            CXXCOMPILER: clang++
            ENABLE_ASSERTIONS: ON

    name: ${{ matrix.name }}
    continue-on-error: ${{ !matrix.continue-on-error == null && false || true }}
    runs-on: ${{ matrix.runs-on }}
    env:
      PUBLISH: OFF

      BUILD_TYPE:           ${{ contains(matrix.name, 'debug') && 'Debug' || 'Release' }}
      ENABLE_CONAN:         ${{ contains(matrix.name, 'conan') && 'ON' || 'OFF' }}
      ENABLE_NODE_BINDINGS: ${{ contains(matrix.name, 'node')  && 'ON' || 'OFF' }}
      NODE_PACKAGE_TESTS:   ${{ contains(matrix.name, 'node')  && 'ON' || 'OFF' }}
      BUILD_NODE_PACKAGE:   ${{ contains(matrix.name, 'node')  && 'ON' || 'OFF' }}

      BUILD_SHARED_LIBS: ${{ matrix.BUILD_SHARED_LIBS }}
      CCOMPILER:         ${{ matrix.CCOMPILER }}
      CFLAGS:            ${{ matrix.CFLAGS }}
      CXXCOMPILER:       ${{ matrix.CXXCOMPILER }}
      CXXFLAGS:          ${{ matrix.CXXFLAGS }}

      ENABLE_ASSERTIONS: ${{ matrix.ENABLE_ASSERTIONS }}
      ENABLE_CLANG_TIDY: ${{ matrix.ENABLE_CLANG_TIDY }}
      ENABLE_COVERAGE:   ${{ matrix.ENABLE_COVERAGE }}
      ENABLE_ASAN:       ${{ matrix.ENABLE_ASAN }}
      ENABLE_UBSAN:      ${{ matrix.ENABLE_UBSAN }}
      UNIT_TESTS:        ${{ (matrix.UNIT_TESTS != 'OFF'        ) && 'ON' || 'OFF' }}
      NODEJS_TESTS:      ${{ (matrix.NODEJS_TESTS != 'OFF'      ) && 'ON' || 'OFF' }}
      CUCUMBER_TESTS:    ${{ (matrix.CUCUMBER_TESTS != 'OFF'    ) && 'ON' || 'OFF' }}
      ENABLE_LTO:        ${{ matrix.ENABLE_LTO }}

    steps:
      - uses: actions/checkout@v4
      - name: Build machine architecture
        run: uname -m

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: npm

      # PIP install Conan and cache it

      - name: Restore Python cache
        uses: actions/cache/restore@v4
        id: cache-python-restore
        if: ${{ env.ENABLE_CONAN == 'ON' }}
        with:
          path: .venv
          key: python-${{ matrix.runs-on }}-${{ hashFiles('requirements-dev.txt') }}

      - name: Pip Install requirements
        if: ${{ env.ENABLE_CONAN == 'ON' && steps.cache-python-restore.outputs.cache-hit != 'true' }}
        run: |
          python3 -m venv .venv
          source .venv/bin/activate
          python3 -m pip install -r requirements-dev.txt

      - name: Save Python cache
        uses: actions/cache/save@v4
        if: ${{ env.ENABLE_CONAN == 'ON' && steps.cache-python-restore.outputs.cache-hit != 'true' }}
        with:
          path: .venv
          key: ${{ steps.cache-python-restore.outputs.cache-primary-key }}

      # Conan cache

      - name: Restore Conan cache
        uses: actions/cache/restore@v4
        if: ${{ env.ENABLE_CONAN == 'ON' }}
        id: cache-conan-restore
        with:
          path: ${{ env.CONAN_HOME }}
          key: conan-${{ matrix.runs-on }}-${{ env.BUILD_TYPE }}-${{ hashFiles('conanfile.py') }}

      # CCache

      - name: Restore CCache
        id: cache-ccache-restore
        uses: actions/cache/restore@v4
        if: ${{ env.ENABLE_CCACHE == 'ON' }}
        with:
          path: ${{ env.CCACHE_DIR }}
          key: ccache-${{ matrix.name }}-${{ github.sha }}
          restore-keys: |
            ccache-${{ matrix.name }}-

      - name: Prepare environment
        run: |
          mkdir -p "$CCACHE_DIR"

          PACKAGE_JSON_VERSION=$(node -e "console.log(require('./package.json').version)")
          echo PUBLISH=$([[ "${GITHUB_REF:-}" == "refs/tags/v${PACKAGE_JSON_VERSION}" ]] && echo "On" || echo "Off") >> $GITHUB_ENV
          echo "OSRM_INSTALL_DIR=${GITHUB_WORKSPACE}/install-osrm" >> $GITHUB_ENV
          echo "OSRM_BUILD_DIR=${GITHUB_WORKSPACE}/build-osrm" >> $GITHUB_ENV
          echo "TEST_DIR=${GITHUB_WORKSPACE}/test" >> $GITHUB_ENV
          if [[ "$ENABLE_ASAN" == "ON" || "$ENABLE_UBSAN" == "ON" ]]; then
            CI_DIR=${GITHUB_WORKSPACE}/scripts/ci
            # We can only set this after checkout once we know the workspace directory
            echo "ASAN_OPTIONS=log_path=${LOG_DIR}/asan.log:print_suppressions=0:suppressions=${CI_DIR}/addresssanitizer.conf" >> $GITHUB_ENV
            echo "LSAN_OPTIONS=log_path=${LOG_DIR}/lsan.log:print_suppressions=0:suppressions=${CI_DIR}/leaksanitizer.conf" >> $GITHUB_ENV
            echo "UBSAN_OPTIONS=log_path=${LOG_DIR}/ubsan.log:symbolize=1:halt_on_error=1:print_stacktrace=1:suppressions=${CI_DIR}/undefinedsanitizer.conf" >> $GITHUB_ENV
          fi

          if [[ "${RUNNER_OS}" == "Linux" ]]; then
            echo "JOBS=$((`nproc` + 1))" >>  $GITHUB_ENV
          elif [[ "${RUNNER_OS}" == "macOS" ]]; then
            echo "JOBS=$((`sysctl -n hw.ncpu` + 1))" >>  $GITHUB_ENV
          fi
      # See: https://github.com/actions/toolkit/issues/946#issuecomment-1590016041
      # We need it to be able to access system folders while restoring cached Boost below
      - name: Give tar root ownership
        if: runner.os == 'Linux' && env.ENABLE_CONAN != 'ON'
        run: sudo chown root /bin/tar && sudo chmod u+s /bin/tar

      - name: Install boost
        if: ${{ env.ENABLE_CONAN != 'ON' }}
        uses: MarkusJx/install-boost@v2
        id: install-boost
        with:
          boost_version: 1.88.0
          platform_version: ${{ matrix.BOOST_PLATFORM }}

      - name: Install dev dependencies
        run: |
          # workaround for issue that GitHub Actions seems to not adding it to PATH after https://github.com/actions/runner-images/pull/6499
          # and that's why CI cannot find conan executable installed above
          if [[ "${RUNNER_OS}" == "macOS" ]]; then
            echo "/Library/Frameworks/Python.framework/Versions/Current/bin" >> $GITHUB_PATH
          fi

          # Update package list
          if [[ "${RUNNER_OS}" == "Linux" || "${ENABLE_CONAN}" != "ON" ]]; then
            sudo apt-get update -y
          fi

          # Install compiler and ccache
          if [[ "${RUNNER_OS}" == "Linux" ]]; then
            sudo apt-get install -y ${CCOMPILER} ${CXXCOMPILER} ccache
          elif [[ "${RUNNER_OS}" == "macOS" ]]; then
            brew install ccache
          fi

          # Linux dev packages
          if [[ "${ENABLE_CONAN}" != "ON" ]]; then
            sudo apt-get install -y libbz2-dev libxml2-dev libzip-dev liblua5.2-dev
            if [[ "${ENABLE_COVERAGE}" == "ON" ]]; then
              sudo apt-get install -y lcov
            fi
          fi

          # TBB
          TBB_VERSION=2021.12.0
          if [[ "${RUNNER_OS}" == "Linux" ]]; then
            TBB_URL="https://github.com/oneapi-src/oneTBB/releases/download/v${TBB_VERSION}/oneapi-tbb-${TBB_VERSION}-lin.tgz"
          elif [[ "${RUNNER_OS}" == "macOS" ]]; then
            TBB_URL="https://github.com/oneapi-src/oneTBB/releases/download/v${TBB_VERSION}/oneapi-tbb-${TBB_VERSION}-mac.tgz"
          fi
          wget --tries 5 ${TBB_URL} -O onetbb.tgz
          tar zxvf onetbb.tgz
          sudo cp -a oneapi-tbb-${TBB_VERSION}/lib/. /usr/local/lib/
          sudo cp -a oneapi-tbb-${TBB_VERSION}/include/. /usr/local/include/
      - name: Prepare build
        run: |
          mkdir -p ${OSRM_BUILD_DIR}
          mkdir -p ${TEST_DIR}
          ccache --max-size=256M
          ccache --zero-stats
          npm ci --ignore-scripts
          if [[ "${ENABLE_COVERAGE}" == "ON" ]]; then
            lcov --directory . --zerocounters # clean cached files
          fi
          echo "CC=${CCOMPILER}" >> $GITHUB_ENV
          echo "CXX=${CXXCOMPILER}" >> $GITHUB_ENV
          if [[ "${RUNNER_OS}" == "macOS" ]]; then
            # missing from GCC path, needed for conan builds of libiconv, for example.
            sudo xcode-select --switch /Library/Developer/CommandLineTools
            echo "LIBRARY_PATH=${LIBRARY_PATH}:/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/lib" >> $GITHUB_ENV
            echo "CPATH=${CPATH}:/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include" >> $GITHUB_ENV
          fi
          if [[ "${ENABLE_CONAN}" == "ON" ]]; then
            source .venv/bin/activate
            conan profile detect --force
          fi

      - name: Build and install OSRM
        working-directory: ${{ env.OSRM_BUILD_DIR }}
        run: |
          if [[ "${ENABLE_CONAN}" == "ON" ]]; then
            # conan is also called from cmake
            source ../.venv/bin/activate
          fi

          echo "::group::cmake"
          cmake .. -DCMAKE_BUILD_TYPE=${BUILD_TYPE} \
                   -DENABLE_CONAN=${ENABLE_CONAN:-OFF} \
                   -DENABLE_ASSERTIONS=${ENABLE_ASSERTIONS:-OFF} \
                   -DENABLE_CLANG_TIDY=${ENABLE_CLANG_TIDY:-OFF} \
                   -DBUILD_SHARED_LIBS=${BUILD_SHARED_LIBS:-OFF} \
                   -DENABLE_COVERAGE=${ENABLE_COVERAGE:-OFF} \
                   -DENABLE_NODE_BINDINGS=${ENABLE_NODE_BINDINGS:-OFF} \
                   -DENABLE_ASAN=${ENABLE_ASAN:-OFF} \
                   -DENABLE_UBSAN=${ENABLE_UBSAN:-OFF} \
                   -DENABLE_CCACHE=${ENABLE_CCACHE:-ON} \
                   -DENABLE_LTO=${ENABLE_LTO:-ON} \
                   -DCMAKE_INSTALL_PREFIX=${OSRM_INSTALL_DIR}
          echo "::endgroup::"

          echo "::group::make"
          make --jobs=${JOBS}
          echo "::endgroup::"

          if [[ "${UNIT_TESTS}" == "ON" ]]; then
            if [[ "$ENABLE_ASAN" == 'ON' ]]; then
              export LD_LIBRARY_PATH=$(dirname `clang -print-file-name=libclang_rt.asan-x86_64.so`):$LD_LIBRARY_PATH
            fi
            echo "::group::make tests"
            make --jobs=${JOBS} tests
            echo "::endgroup::"
            echo "::group::make benchmarks"
            make --jobs=${JOBS} benchmarks
            echo "::endgroup::"

            echo "::group::make install"
            sudo make install
            echo "::endgroup::"

            if [[ "${RUNNER_OS}" == "Linux" ]]; then
              echo "LD_LIBRARY_PATH=$LD_LIBRARY_PATH:${OSRM_INSTALL_DIR}/lib" >> $GITHUB_ENV
            fi
            echo "PKG_CONFIG_PATH=${OSRM_INSTALL_DIR}/lib/pkgconfig" >> $GITHUB_ENV
          fi
        env:
          Boost_ROOT: ${{ steps.install-boost.outputs.BOOST_ROOT }}

      - name: Save Conan cache
        uses: actions/cache/save@v4
        if: ${{ always() && env.ENABLE_CONAN == 'ON' && steps.cache-conan-restore.outputs.cache-hit != 'true' }}
        with:
          path: ${{ env.CONAN_HOME }}
          key: ${{ steps.cache-conan-restore.outputs.cache-primary-key }}

      - name: Save CCache
        uses: actions/cache/save@v4
        if: ${{ always() && env.ENABLE_CCACHE == 'ON' && steps.cache-ccache-restore.outputs.cache-hit != 'true' }}
        with:
          path: ${{ env.CCACHE_DIR }}
          key: ${{ steps.cache-ccache-restore.outputs.cache-primary-key }}

      - name: Show CCache statistics
        if: ${{ always() && env.ENABLE_CCACHE == 'ON' }}
        run: |
          ccache -s
          echo "::group::ccache -p"
          ccache -p
          echo "::endgroup::"

      - name: Run unit tests
        if: ${{ env.UNIT_TESTS == 'ON' }}
        working-directory: ${{ env.OSRM_BUILD_DIR }}
        run: |
          make -C ${TEST_DIR}/data benchmark

          if [[ "${RUNNER_OS}" == "macOS" ]]; then
            # macOS SIP strips the linker path. Reset this inside the running shell
            export LD_LIBRARY_PATH=${{ env.LD_LIBRARY_PATH }}
          fi

          for i in unit_tests/*-tests
          do echo "::group::Running $i"
            $i
            echo "::endgroup::"
          done

      - name: Run nodejs tests
        if: ${{ env.NODEJS_TESTS == 'ON' }}
        run: |
          if [[ "$ENABLE_ASAN" == 'ON' ]]; then
            export LD_PRELOAD=`clang -print-file-name=libclang_rt.asan-x86_64.so`:"$LD_PRELOAD"
          fi
          if [[ "$ENABLE_UBSAN" == 'ON' ]]; then
            export LD_PRELOAD=`clang -print-file-name=libclang_rt.ubsan_standalone-x86_64.so`:"$LD_PRELOAD"
          fi
          npm run nodejs-tests

      - name: Run cucumber tests
        if: ${{ env.CUCUMBER_TESTS == 'ON' }}
        run: |
          npm test -- --parallel $JOBS

      - if: ${{ env.NODE_PACKAGE_TESTS == 'ON' }}
        uses: ./.github/actions/node-package-tests.yml

      - name: Upload test logs
        uses: actions/upload-artifact@v4
        if: always()
        with:
          if-no-files-found: ignore
          name: ${{ matrix.name }}-test-logs
          path: ${{ env.LOG_DIR }}

      - name: Build Node package
        if: ${{ env.BUILD_NODE_PACKAGE == 'ON' }}
        run: ./scripts/ci/node_package.sh

      - name: Publish Node package
        if: ${{ env.BUILD_NODE_PACKAGE == 'ON' && env.PUBLISH == 'ON' }}
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifactErrorsFailBuild: true
          artifacts: build/stage/**/*.tar.gz
          omitBody: true
          omitBodyDuringUpdate: true
          omitName: true
          omitNameDuringUpdate: true
          replacesArtifacts: true
          token: ${{ secrets.GITHUB_TOKEN }}

  ci-complete:
    runs-on: ubuntu-latest
    needs: [format-taginfo-docs, docker, windows, build-matrix]
    steps:
      - run: echo "CI complete"
